name: Build and Test
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Package
        run: mvn clean verify
      - name: Test several times
        run: for i in {1..25} ; do mvn surefire:test ; done
      - name: Copy JAR for upload
        run: mkdir staging && cp target/*.jar staging
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
